[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.watchPatterns]
include = ["**/*.js", "**/*.ts", "**/*.jsx", "**/*.tsx", "**/*.json"]
ignore = ["node_modules/**", ".next/**", "out/**"]
