[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build]
watchPatterns = [
  "**/*.js",
  "**/*.ts", 
  "**/*.jsx",
  "**/*.tsx",
  "**/*.json",
  "!node_modules/**",
  "!.next/**",
  "!out/**"
]
